spring.application.name=customerbot

spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672

rabbitmq.queue.name=message_queue

#logging.structured.format.console=logstash

